### ISSUE TITLE
image 경로 수정 요청

### ISSUE THREAD

**Issue by bumheehan** [DICEPT/starbucks_clone#1]
일부 이미지 경로가 root(/)로 되어 있어서 이미지가 안보여요.
./로 수정해주세요

**Comment by bumheehan** [comment]
상대 경로, 절대 경로 확인해주시고 추가로 Vue나 React에서 이미지 경로 어떻게 처리 되는지 아시면 좋을거같아요.

**Comment by DICEPT** [comment]
발견해줘서 감사해요! 피드백 내용으로 이미지 경로 수정했어요! :)
